/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class macsim_internal_Server */

#ifndef _Included_macsim_internal_Server
#define _Included_macsim_internal_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     macsim_internal_Server
 * Method:    serverMain
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_macsim_internal_Server_serverMain
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     macsim_internal_Server
 * Method:    terminateServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_macsim_internal_Server_terminateServer
  (JNIEnv *, jobject);

/*
 * Class:     macsim_internal_Server
 * Method:    setNameVariables
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_macsim_internal_Server_setNameVariables
  (JNIEnv *, jobject);

/*
 * Class:     macsim_internal_Server
 * Method:    getInBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_macsim_internal_Server_getInBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     macsim_internal_Server
 * Method:    getOutBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_macsim_internal_Server_getOutBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     macsim_internal_Server
 * Method:    serverFunc
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_macsim_internal_Server_serverFunc
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
