/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class macsim_internal_Server_ServerThread */

#ifndef _Included_macsim_internal_Server_ServerThread
#define _Included_macsim_internal_Server_ServerThread
#ifdef __cplusplus
extern "C" {
#endif
#undef macsim_internal_Server_ServerThread_MIN_PRIORITY
#define macsim_internal_Server_ServerThread_MIN_PRIORITY 1L
#undef macsim_internal_Server_ServerThread_NORM_PRIORITY
#define macsim_internal_Server_ServerThread_NORM_PRIORITY 5L
#undef macsim_internal_Server_ServerThread_MAX_PRIORITY
#define macsim_internal_Server_ServerThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
