mex -outdir ..\bin ...
sim_functions.cpp ...
sim_class.cpp ...
sim_interface_container.cpp ...
sim_interface.cpp ...
sim_exception.cpp ...
sim_vector.cpp ...
../../../MatrixClassLib/code/src/matrix.cpp ...
../../../MatrixClassLib/code/src/matrix_operator.cpp ...
../../../MatrixClassLib/code/src/matrix_access.cpp ...
-c -v